name: Workflow Cleanup Bot
on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  job1:
    name: Cleanup
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: List files
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name }}"
          RUN_ID=$(curl -s -X GET -H "Authorization: token $TOKEN" "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/runs" | jq -r '.workflow_runs[].id')
          echo $RUN_ID
        #   for id in $RUN_ID; do
        #       curl -s -X DELETE -H "Authorization: token $TOKEN" "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/runs/$id"
        #   done
