name: Delete workflow runs
on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  job1:
    name: Cleanup
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: List files
        run: |
          ls
