name: update-registry-and-assets

on:
  push:
    branches:
      - "main"
    paths:
      - blockchains/
  pull_request:
    branches:
      - "main"
    paths:
      - blockchains/

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Bun.sh
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.0.22"

      - name: run update script
        run: bun i && bun registry && bun assets

      - name: Commit and Push Changes
        run: |
          if [[ $(git status --porcelain) ]]; then
             git config user.name "ppegu"
             git config user.email "pranpegu997@gmail.com"
             git pull origin main
             git add .
             git commit -m "Update registry and assets"
             git push origin main
          else
             echo "No changes to commit."
          fi
